#!/bin/sh

sed -i 's/misolabel=BIGLINUXLIVE/misolabel=XIVAStudio/' /usr/bin/grub-fix.sh
#troca titulo janela BBV
# # sed -i 's/Instalar o BigLinux/Instalar o XIVAStudio/' /usr/bin/calamares-biglinux
sed -i 's/BigLinux/XIVAStudio/' /usr/bin/calamares-biglinux
# # sed -i 's/Instalar o BigLinux/Instalar o XIVAStudio/' /usr/bin/calamares
# sed -i 's/https\:\/\/www.biglinux.com.br/https\:\/\/www.xivastudio.org/'  /usr/share/calamares/branding/biglinux/branding.desc
#troca nome na 1º tela
sed -i 's/BigLinux/XIVAStudio/' /usr/share/calamares/branding/biglinux/branding.desc
#troca logo cantinho da primeira tela do calamares
# rm /usr/share/calamares/branding/biglinux/logo.png
cp /usr/share/calamares/branding/biglinux/logo-xiva.png  /usr/share/calamares/branding/biglinux/logo.png
#troca logo do centro
sed -i 's/big-welcome.svg/xiva-welcome.svg/' /usr/share/calamares/branding/biglinux/branding.desc
sed -i 's/logo.svg/logo-xiva.svg/' /usr/share/calamares/branding/biglinux/calamares-sidebar.qml

# sed -i 's/biglinux/xivastudio/' /usr/share/calamares/branding/biglinux/branding.desc
# sed -i 's/big/xiva/' /usr/share/calamares/branding/biglinux/branding.desc


#troca logo do BBV calamares
# # sed -i 's/logo.svg/logo-xiva.svg/' /usr/share/bigbashview/bcc/apps/bigbashview-calamares/index.sh.htm

#trocar icone do instalador calamares
sed -i 's/big/xiva/' /usr/share/applications/com.biglinux.calamares-config.desktop

# #troca slide
# cd /usr/share/calamares/branding/biglinux/en
# rm 00.jpg
# mv 00-xiva.jpg 00.jpg
# rm 04.jpg
# mv 04-xiva.jpg 04.jpg
# cd /usr/share/calamares/branding/biglinux/es
# rm 00.jpg
# mv 00-xiva.jpg 00.jpg
# rm 04.jpg
# mv 04-xiva.jpg 04.jpg
# cd /usr/share/calamares/branding/biglinux/pt
# rm 00.jpg
# mv 00-xiva.jpg 00.jpg
# rm 04.jpg
# mv 04-xiva.jpg 04.jpg

